const {chromium}=require(process.env.WEATHERBRIDGE_PLAYWRIGHT||'playwright');
const fs=require('node:fs'),assert=require('node:assert/strict');
const base='http://127.0.0.1:8017/',out='.cache/journey-qa';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launchPersistentContext(out+'/chrome',{headless:true,executablePath:process.env.WEATHERBRIDGE_BROWSER,args:['--enable-unsafe-swiftshader'],viewport:{width:1440,height:1000}});
const page=await browser.newPage(),errors=[],missing=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)missing.push(r.url());});
try{
for(const width of [1522,1440,768,390,320]){await page.setViewportSize({width,height:1000});await page.goto(base+'?lang=zh',{waitUntil:'networkidle'});await page.waitForSelector('.price-row');
assert.deepEqual(await page.locator('main>section[id]').evaluateAll(es=>es.map(e=>e.id)),['hero','jinxi','malawi','mexico','polymarket','why-polymarket','evidence','action','reflection']);
for(const lang of ['zh','en']){await page.locator('[data-language='+lang+']').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+width+' '+lang);assert.equal(await page.locator('.case-entry,.story-steps,.chapterbar').count(),0);await page.locator('#unit').selectOption('F');await page.waitForFunction(()=>document.querySelector('#evidence-values').textContent.includes('°F'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Fahrenheit overflow '+width+' '+lang);await page.locator('#unit').selectOption('C');await page.waitForFunction(()=>document.querySelector('#evidence-values').textContent.includes('°C'));await page.evaluate(()=>scrollTo(0,0));}
await page.locator('[data-language=zh]').click();
if([1440,390,1522].includes(width)){await page.screenshot({path:out+'/hero-'+width+'.png'});for(const id of ['jinxi','malawi','evidence','action']){await page.locator('#'+id).scrollIntoViewIfNeeded();await page.waitForTimeout(400);await page.screenshot({path:out+'/'+id+'-'+width+'.png'});}}
console.log('PASS responsive bilingual '+width);}
await page.setViewportSize({width:1440,height:1000});await page.goto(base+'?lang=zh');await page.waitForSelector('.price-row');
for(const city of ['mexico','laguardia']){await page.locator('.evidence-controls summary').click();await page.locator('#place').selectOption(city);await page.waitForFunction(c=>document.querySelector('#evidence-date').textContent.includes(c),city==='mexico'?'MMMX':'KLGA');for(const date of ['2026-09-19','2026-09-23','2026-09-27']){await page.locator('#date').selectOption(date);await page.waitForFunction(d=>document.querySelector('#evidence-date').textContent.includes(d),date);const verdict=await page.locator('#evidence-verdict').innerText();await page.locator('#unit').selectOption('F');await page.waitForFunction(()=>document.querySelector('#evidence-values').textContent.includes('°F'));assert.equal(await page.locator('#evidence-verdict').innerText(),verdict);await page.locator('#unit').selectOption('C');await page.waitForFunction(()=>document.querySelector('#evidence-values').textContent.includes('°C'));}
await page.locator('.evidence-controls summary').click();}
console.log('PASS city/date/unit invariant');
for(const weather of ['rain','sun'])for(const choice of ['all','batch','cover','store']){await page.goto(base+'?lang=zh&replay='+weather+'&test='+choice+'#action');await page.locator('#action').scrollIntoViewIfNeeded();await page.waitForSelector('#first-choice:not([hidden])');await page.locator('[data-first=information]').click();await page.locator('[data-choice='+choice+']').click();await page.locator('#reveal-weather').click();assert.equal(await page.locator('.review-row').count(),4);assert.ok(await page.locator('.review-row.selected').innerText());assert.equal(await page.locator('#debrief-link').getAttribute('href'),'#reflection');console.log('PASS '+weather+' '+choice);}
console.log('PASS eight inline exercise states');
await page.locator('#debrief-link').click();await page.screenshot({path:out+'/reflection-1440.png'});
await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base+'?lang=en#action');await page.locator('#action').scrollIntoViewIfNeeded();await page.waitForSelector('#first-choice:not([hidden])');await page.locator('.exercise-options summary').click();await page.locator('#text-mode').click();await page.locator('[data-first=store]').click();await page.locator('#reveal-weather').click();assert.equal(await page.locator('.review-row').count(),4);assert.ok(await page.locator('#fallback-note').isVisible());
await page.locator('#restart-game').click();await page.locator('#start-game').click();await page.waitForSelector('#first-choice:not([hidden])');assert.equal(await page.locator('.review-row').count(),0);console.log('PASS reduced motion / text alternative / restart clears review');
for(const [path,hash] of [['cases/jinxi/','#jinxi'],['cases/malawi/','#malawi'],['cases/mexico-city/','#mexico'],['signals/guide/','#evidence'],['signals/introduction/','#polymarket'],['experience/food-drying/','#action'],['experience/food-drying/debrief/?choice=cover&weather=rain','#reflection']]){await page.goto(base+path+(path.includes('?')?'&':'?')+'lang=en',{waitUntil:'networkidle'});assert.equal(new URL(page.url()).hash,hash);assert.ok(page.url().includes('lang=en'));}
await page.waitForSelector('.review-row');assert.equal(await page.locator('.review-row').count(),4);
await page.goto(base+'research/?lang=zh',{waitUntil:'networkidle'});await page.waitForSelector('#source-record h3');await page.locator('#source-place').selectOption('laguardia');await page.waitForFunction(()=>document.querySelector('#source-record h3').textContent.includes('KLGA'));await page.locator('#source-date').selectOption('2026-09-27');await page.waitForFunction(()=>document.querySelector('#source-record h3').textContent.includes('2026-09-27'));await page.screenshot({path:out+'/research-1440.png',fullPage:true});
assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);fs.writeFileSync(out+'/report.json',JSON.stringify({errors,missing,responsive:[1522,1440,768,390,320],gameStates:8,unitInvariant:true,legacyRoutes:7},null,2));console.log('PASS research, legacy routes, no JS errors / missing assets');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
